### PR TITLE
Fix data race in query execution

### LINKED ISSUE #101: Possible data race in the query executor
Running the test suite with the data race detector enabled reveals a possible data race:

```==================
WARNING: DATA RACE
Write at 0x00c000153858 by goroutine 105:
  sync/atomic.AddInt32()
      /usr/local/go/src/runtime/race_amd64.s:292 +0xb
  github.com/movio/bramble.(*queryExecution).executeChildStep()
      /Users/nmaquet/Workspace/bramble/query_execution.go:152 +0x6b
  github.com/movio/bramble.(*queryExecution).executeChildStep.func1()
      /Users/nmaquet/Workspace/bramble/query_execution.go:190 +0x69
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/nmaquet/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Previous read at 0x00c000153858 by goroutine 44:
  github.com/movio/bramble.(*queryExecution).executeChildStep()
      /Users/nmaquet/Workspace/bramble/query_execution.go:153 +0x7c
  github.com/movio/bramble.(*queryExecution).executeChildStep.func1()
      /Users/nmaquet/Workspace/bramble/query_execution.go:190 +0x69
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/nmaquet/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Goroutine 105 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /Users/nmaquet/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x73
  github.com/movio/bramble.(*queryExecution).executeChildStep()
      /Users/nmaquet/Workspace/bramble/query_execution.go:189 +0x6fc
  github.com/movio/bramble.(*queryExecution).executeRootStep.func1()
      /Users/nmaquet/Workspace/bramble/query_execution.go:126 +0x69
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/nmaquet/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Goroutine 44 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /Users/nmaquet/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x73
  github.com/movio/bramble.(*queryExecution).executeChildStep()
      /Users/nmaquet/Workspace/bramble/query_execution.go:189 +0x6fc
  github.com/movio/bramble.(*queryExecution).executeRootStep.func1()
      /Users/nmaquet/Workspace/bramble/query_execution.go:126 +0x69
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/nmaquet/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94
==================
--- FAIL: TestQueryExecutionMultipleServicesWithArray (0.01s)
    testing.go:1092: race detected during execution of test
```

### PR DESCRIPTION
**Pull request by nmaquet**
Resolves #101

### CODE REVIEW

File: query_execution.go [hunk 1]
```diff
@@ -149,10 +149,13 @@ func (q *queryExecution) writeExecutionResult(step *QueryPlanStep, data interfac
 }
 
 func (q *queryExecution) executeChildStep(step *QueryPlanStep, boundaryIDs []string) error {
-	atomic.AddInt32(&q.requestCount, 1)
```
Comment (lucianjon) [inline query_execution.go:152]: You could get rid of the unlock in both branches with something like:

```
func (q *queryExecution) incrementAndReturnRequestCount() int32 {
    q.mutex.Lock()
    defer q.mutex.Unlock()
    q.requestCount += 1
    return q.requestCount
}
```

**Review by lucianjon — APPROVED** [review]
LGTM

File: query_execution.go (hunk 1 above)
Comment (nmaquet) [reply query_execution.go:152]: You could but you'd make the entire func into a critical section and all steps would run sequentially instead of in parallel :)

**Comment by andyyu2004** [comment]
Hey @nmaquet, I think the initial problem was doing an atomic store but not an atomic read. Replacing `if q.requestCount > q.maxRequest` with `atomic.LoadInt32(&q.requestCount) > q.maxRequest` seems to do the trick. I think using atomics is far nicer than using a trivial mutex.
